### ISSUE TITLE
[feature] Custom Redis cache KEY

### ISSUE THREAD

**Issue by rts-gordon** [asjdf/gorm-cache#11]
Hi @asjdf 
 Would you like to plan this feature: client can custom the Redis cache KEY? So many new features can be implemented, like multi tenant.

  Thank you.

**Comment by asjdf** [comment]
Hi,
Thank you very much for your suggestion, I want to make sure you care about consistency before accepting this suggestion? Because if the same data table does not share the cache pool, the information may be inconsistent (this is fatal in some cases)

In fact, I also looking for `customize the cache key` feature, but this feature does not seem to be so closely related to multi-tenancy. Before supporting multi-tenancy, the first issue we have to solve is the low primaryCache hit rate. (The original code did not handle this problem very well. Obviously, it may take a lot of time to implement this feature. We can try to work together to achieve this feature)

Thank you.

**Comment by rts-gordon** [comment]
yes, we can enhance those features.
